language: node_js

# Node 18 binaries require glibc >= 2.28
dist: focal

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'stable'
  - '18'
  - '16'
  - '14'

# Lint errors should trigger a failure.
before_script:
  - npm run lint:ci
  - npm run build

# Runs the coverage script (which runs the tests)
script: npm run coveralls
